## Preprocessing

In [42]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [43]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df_org = application_df.copy()
#df_lend_data.drop(columns="loan_status")
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [44]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [45]:
# Look at APPLICATION_TYPE value counts for binning
application_type_count = application_df['APPLICATION_TYPE'].value_counts()

application_type_count

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [46]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#application_type_count_below_1000 = application_type_count[application_type_count < 1000].index
application_types_to_replace = application_type_count[application_type_count < 500].index
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [47]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df['CLASSIFICATION'].value_counts()

classification_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [48]:
# You may find it helpful to look at CLASSIFICATION value counts >1

classification_count[classification_count > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [49]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_count[classification_count < 1000].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [52]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_dummies = pd.get_dummies(application_df)
application_df_dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 44 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   STATUS                        34299 non-null  int64
 1   ASK_AMT                       34299 non-null  int64
 2   IS_SUCCESSFUL                 34299 non-null  int64
 3   APPLICATION_TYPE_Other        34299 non-null  bool
 4   APPLICATION_TYPE_T10          34299 non-null  bool
 5   APPLICATION_TYPE_T19          34299 non-null  bool
 6   APPLICATION_TYPE_T3           34299 non-null  bool
 7   APPLICATION_TYPE_T4           34299 non-null  bool
 8   APPLICATION_TYPE_T5           34299 non-null  bool
 9   APPLICATION_TYPE_T6           34299 non-null  bool
 10  APPLICATION_TYPE_T7           34299 non-null  bool
 11  APPLICATION_TYPE_T8           34299 non-null  bool
 12  AFFILIATION_CompanySponsored  34299 non-null  bool
 13  AFFILIATION_Family/Parent     34299 non-null  bool
 14  AFFILIATION_Independent       34299 non-null  bool
 15  AFFILIATION_National          34299 non-null  bool
 16  AFFILIATION_Other             34299 non-null  bool
 17  AFFILIATION_Regional          34299 non-null  bool
 18  CLASSIFICATION_C1000          34299 non-null  bool
 19  CLASSIFICATION_C1200          34299 non-null  bool
 20  CLASSIFICATION_C2000          34299 non-null  bool
 21  CLASSIFICATION_C2100          34299 non-null  bool
 22  CLASSIFICATION_C3000          34299 non-null  bool
 23  CLASSIFICATION_Other          34299 non-null  bool
 24  USE_CASE_CommunityServ        34299 non-null  bool
 25  USE_CASE_Heathcare            34299 non-null  bool
 26  USE_CASE_Other                34299 non-null  bool
 27  USE_CASE_Preservation         34299 non-null  bool
 28  USE_CASE_ProductDev           34299 non-null  bool
 29  ORGANIZATION_Association      34299 non-null  bool
 30  ORGANIZATION_Co-operative     34299 non-null  bool
 31  ORGANIZATION_Corporation      34299 non-null  bool
 32  ORGANIZATION_Trust            34299 non-null  bool
 33  INCOME_AMT_0                  34299 non-null  bool
 34  INCOME_AMT_1-9999             34299 non-null  bool
 35  INCOME_AMT_10000-24999        34299 non-null  bool
 36  INCOME_AMT_100000-499999      34299 non-null  bool
 37  INCOME_AMT_10M-50M            34299 non-null  bool
 38  INCOME_AMT_1M-5M              34299 non-null  bool
 39  INCOME_AMT_25000-99999        34299 non-null  bool
 40  INCOME_AMT_50M+               34299 non-null  bool
 41  INCOME_AMT_5M-10M             34299 non-null  bool
 42  SPECIAL_CONSIDERATIONS_N      34299 non-null  bool
 43  SPECIAL_CONSIDERATIONS_Y      34299 non-null  bool
dtypes: bool(41), int64(3)
memory usage: 2.1 MB

In [65]:
# Split our preprocessed data into our features and target arrays
y = application_df_dummies["IS_SUCCESSFUL"]
X = application_df_dummies.drop(columns="IS_SUCCESSFUL")

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    random_state=1,
                                                    stratify=y)
X_train.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   STATUS                        34299 non-null  int64
 1   ASK_AMT                       34299 non-null  int64
 2   APPLICATION_TYPE_Other        34299 non-null  bool
 3   APPLICATION_TYPE_T10          34299 non-null  bool
 4   APPLICATION_TYPE_T19          34299 non-null  bool
 5   APPLICATION_TYPE_T3           34299 non-null  bool
 6   APPLICATION_TYPE_T4           34299 non-null  bool
 7   APPLICATION_TYPE_T5           34299 non-null  bool
 8   APPLICATION_TYPE_T6           34299 non-null  bool
 9   APPLICATION_TYPE_T7           34299 non-null  bool
 10  APPLICATION_TYPE_T8           34299 non-null  bool
 11  AFFILIATION_CompanySponsored  34299 non-null  bool
 12  AFFILIATION_Family/Parent     34299 non-null  bool
 13  AFFILIATION_Independent       34299 non-null  bool
 14  AFFILIATION_National          34299 non-null  bool
 15  AFFILIATION_Other             34299 non-null  bool
 16  AFFILIATION_Regional          34299 non-null  bool
 17  CLASSIFICATION_C1000          34299 non-null  bool
 18  CLASSIFICATION_C1200          34299 non-null  bool
 19  CLASSIFICATION_C2000          34299 non-null  bool
 20  CLASSIFICATION_C2100          34299 non-null  bool
 21  CLASSIFICATION_C3000          34299 non-null  bool
 22  CLASSIFICATION_Other          34299 non-null  bool
 23  USE_CASE_CommunityServ        34299 non-null  bool
 24  USE_CASE_Heathcare            34299 non-null  bool
 25  USE_CASE_Other                34299 non-null  bool
 26  USE_CASE_Preservation         34299 non-null  bool
 27  USE_CASE_ProductDev           34299 non-null  bool
 28  ORGANIZATION_Association      34299 non-null  bool
 29  ORGANIZATION_Co-operative     34299 non-null  bool
 30  ORGANIZATION_Corporation      34299 non-null  bool
 31  ORGANIZATION_Trust            34299 non-null  bool
 32  INCOME_AMT_0                  34299 non-null  bool
 33  INCOME_AMT_1-9999             34299 non-null  bool
 34  INCOME_AMT_10000-24999        34299 non-null  bool
 35  INCOME_AMT_100000-499999      34299 non-null  bool
 36  INCOME_AMT_10M-50M            34299 non-null  bool
 37  INCOME_AMT_1M-5M              34299 non-null  bool
 38  INCOME_AMT_25000-99999        34299 non-null  bool
 39  INCOME_AMT_50M+               34299 non-null  bool
 40  INCOME_AMT_5M-10M             34299 non-null  bool
 41  SPECIAL_CONSIDERATIONS_N      34299 non-null  bool
 42  SPECIAL_CONSIDERATIONS_Y      34299 non-null  bool
dtypes: bool(41), int64(2)
memory usage: 1.9 MB

In [56]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [57]:
!pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: keras in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (24.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.31.0)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2024.2.2)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

In [66]:
# Testing models with keras_tuner

# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])

    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=40,
        step=2), activation=activation, input_dim=43))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=20,
            step=2),
            activation=activation))

    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])

    return nn_model

In [67]:
# Import the kerastuner library
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=2)

Reloading Tuner from ./untitled_project/tuner0.json

In [68]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

Trial 56 Complete [00h 00m 50s]
val_accuracy: 0.728863000869751

Best val_accuracy So Far: 0.7323614954948425
Total elapsed time: 00h 36m 42s

In [70]:
# Get best model hyperparameters
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

{'activation': 'relu',
 'first_units': 29,
 'num_layers': 4,
 'units_0': 39,
 'units_1': 29,
 'units_2': 27,
 'units_3': 9,
 'units_4': 13,
 'units_5': 5,
 'tuner/epochs': 20,
 'tuner/initial_epoch': 0,
 'tuner/bracket': 0,
 'tuner/round': 0}

In [71]:
# Evaluate best model against full test data
best_model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5534 - accuracy: 0.7324 - 919ms/epoch - 3ms/step
Loss: 0.5534369349479675, Accuracy: 0.7323614954948425

In [74]:
# Export our model to HDF5 file
best_model.save_weights("AlphabetSoupCharity_Optimization.h5")